use k0sctl to deploy k0s on conformance hosts
Signed-off-by: Karen Almog <kalmog@mirantis.com>

diff --git a/.github/workflows/check-network.yaml b/.github/workflows/check-network.yaml
--- a/.github/workflows/check-network.yaml
+++ b/.github/workflows/check-network.yaml
@@ -1,5 +1,6 @@
 name: k0s Check Network
 on:
+  pull_request:
   workflow_dispatch:
     inputs:
       prNumber:
@@ -9,18 +10,23 @@ on:
     - cron: "0 23 * * *"
 
 jobs:
-  terraform:
+  check-network:
     env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_DEFAULT_REGION: eu-west-1
       TF_VERSION: 1.2.2
+      SONOBUOY_VERSION: 0.56.7
 
     name: "K8s Network Conformance Testing"
     runs-on: ubuntu-latest
+    outputs:
+      k0s_version: ${{ steps.bin_info.outputs.K0S_VERSION }}
+      kubernetes_version: ${{ steps.k0s_build.outputs.KUBERNETES_VERSION }}
+
     defaults:
       run:
-        working-directory: ./inttest/terraform/test-cluster
+        working-directory: ./inttest/sonobuoy/terraform
     steps:
       - name: Get PR Reference
         env:
@@ -41,6 +47,8 @@ jobs:
         uses: actions/checkout@v3
         with:
           ref: ${{ env.github_ref }}
+          # Dev builds rely on "git describe --tags" to set the binary version
+          fetch-depth: 0
 
       - name: Prepare build environment
         working-directory: ./
@@ -59,61 +67,107 @@ jobs:
       - name: Terraform Init
         run: terraform init
 
-      - name: Prepare Environment
-        env:
-          GITHUB_SHA: ${{ github.sha }}
-          GITHUB_REF: ${{ github.ref }}
-        run: ./scripts/prepare-env.sh
+      - name: Cache embedded binaries
+        uses: actions/cache@v3
+        with:
+          key: ${{ runner.os }}-embedded-bins-linux-${{ hashFiles('embedded-bins/**/*') }}
+          path: |
+            .bins.linux.stamp
+            bindata_linux
+            embedded-bins/staging/linux/bin/
+            embedded-bins/Makefile.variables
+            pkg/assets/zz_generated_offsets_linux.go
+      - name: Cache GOCACHE
+        uses: actions/cache@v3
+        with:
+          key: ${{ runner.os }}-build-gocache-linux-${{ github.ref_name }}-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-build-gocache-linux-${{ github.ref_name }}-
+          path: |
+            build/cache/go/build
+      - name: Cache GOMODCACHE
+        uses: actions/cache@v3
+        with:
+          key: ${{ runner.os }}-build-gomodcache-linux-${{ hashFiles('go.sum') }}
+          path: |
+            build/cache/go/mod
+
+      - name: Build k0s Binary
+        id: k0s_build
+        run: |
+          make build
+          echo ::set-output name=KUBERNETES_VERSION::$(make print-kubernetes_version)
+        working-directory: ./
+
+      - name: Set k0s' Version
+        id: bin_info
+        run: |
+          # run k0s version
+          export ROOTDIR=${{ github.workspace }}
+
+          K0S_VER=$($ROOTDIR/k0s version)
+
+          if [ ${K0S_VER} == "" ]; then
+            echo "empty k0s version. failing..."
+            exit 1
+          fi
+
+          echo ::set-output name=K0S_VERSION::${K0S_VER}
 
       - name: Terraform Apply
         run: |
-          export TF_VAR_cluster_name=$(cat CLUSTER_NAME)
+          PR_NUMBER=$(echo ${GITHUB_REF} | cut -d / -f 3 )
+          export TF_VAR_cluster_name="k0s_pr_${PR_NUMBER}"
+          export TF_VAR_k0s_version=${{ steps.bin_info.outputs.K0S_VERSION }}
+
+          # debug
+          echo "k0s_version = ${TF_VAR_k0s_version}"
 
           # Start SSH Agent
           eval `ssh-agent -s`
 
           terraform apply -auto-approve
 
-      - name: Bindata
-        uses: actions/cache@v3
-        id: generated-bindata
-        with:
-          path: |
-            .bins.linux.stamp
-            embedded-bins/staging/linux/bin/
-            bindata
-            pkg/assets/zz_generated_offsets_linux.go
+      - name: Create k0s Cluster using k0sctl
+        id: k0sctl
+        run: |
+          # install k0sctl
+          go install github.com/k0sproject/k0sctl@latest
 
-          key: ${{ runner.os }}-embedded-bins-${{ hashFiles('**/embedded-bins/**/*') }}
-          restore-keys: |
-            ${{ runner.os }}-embedded-bins-${{ hashFiles('**/embedded-bins/**/*') }}
+          k0sctl apply -c k0sctl.yaml
 
-      - name: Build k0s Binary
-        run: make build
+          # save kubeconfig file
+          k0sctl kubeconfig > ${{ github.workspace }}/kubeconfig
+
+      - name: Download Sonobuoy
+        run: |
+          wget https://github.com/vmware-tanzu/sonobuoy/releases/download/v${{ env.SONOBUOY_VERSION }}/sonobuoy_${{ env.SONOBUOY_VERSION }}_linux_amd64.tar.gz
+          sudo mv sonobuoy /usr/local/bin
+          sudo chmod +x /usr/local/bin/sonobuoy
+      - name: Run Sonobuoy
+        run: |
+          export KUBECONFIG=${{ github.workspace }}/kubeconfig
+          sonobuoy run --wait=1200 --plugin=e2e --plugin-env=e2e.E2E_USE_GO_RUNNER=true \
+            --e2e-focus='\[sig-network\].*\[Conformance\]' \
+            --e2e-skip='\[Serial\]' --e2e-parallel=y \
+            --kubernetes-version=v${{ steps.k0s_build.outputs.KUBERNETES_VERSION }}
+
         working-directory: ./
-
-      - name: Deploy k0s to Hosts
-        run: |
-          terraform output -json > out.json
-          ./scripts/deploy-k0s.sh
-
-      - name: Check Network
-        run: |
-          make check-network-vm
-        working-directory: ./inttest
-
       - name: Terraform Destroy
         run: |
-          export TF_VAR_cluster_name=$(cat CLUSTER_NAME)
+          PR_NUMBER=$(echo ${GITHUB_REF} | cut -d / -f 3 )
+          export TF_VAR_cluster_name="k0s_pr_${PR_NUMBER}"
+          export TF_VAR_k0s_version=${{ steps.bin_info.outputs.K0S_VERSION }}
+
           terraform destroy -auto-approve
         if: ${{ always() }}
 
-      - name: slack notify
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-        uses: 8398a7/action-slack@v3
-        with:
-          job_name: "K8s Network Conformance Testing"
-          status: ${{ job.status }}
-          fields: workflow,ref,commit,author,job,took # selectable (default: repo,message)
-        if: ${{ always() }} # Pick up events even if the job fails or is canceled.
+      # - name: slack notify
+      #   env:
+      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      #   uses: 8398a7/action-slack@v3
+      #   with:
+      #     job_name: "K8s Network Conformance Testing"
+      #     status: ${{ job.status }}
+      #     fields: workflow,ref,commit,author,job,took # selectable (default: repo,message)
+      #   if: ${{ always() }} # Pick up events even if the job fails or is canceled.
